Что выведет программа? Объяснить вывод программы. Объяснить внутреннее устройство интерфейсов и их отличие от пустых интерфейсов.
```go
package main

import (
    "fmt"
    "os" 
)

func Foo() error {
    var err *os.PathError = nil
    return err
}

func main() {
    err := Foo()
    fmt.Println(err)
    fmt.Println(err == nil)
}
```
Ответ:
```text
Программа выведет
<nil>
false
```
В go интерфейс представлен либо структурой ```iface```:
```go
type iface struct{
    tab  *itab          //указатель на структуру itab, хранящую данные о типе и списке методов
    data unsafe.Pointer //указатель на конкретную переменную
}

type itab struct {
	inter *interfacetype
	_type *_type
	hash  uint32
	_     [4]byte
	fun   [1]uintptr
}
```
Либо структурой ```eface```(пустой интерфейс):
```go
type eface struct{
    _type  *_type       //указатель на структуру, описывающую конкретный статический тип
    data unsafe.Pointer //указатель на конкретную переменную
}
```

В функции ```Foo()``` мы создаём переменную типа указатель на тип ```os.PathError```.
Тип ```os.PathError``` - это копия типа ```fs.PathError```(вместе с методами).

```go
type PathError = fs.PathError
```
Тип ```PathError``` из пакета fs представляет собой структуру, реализующую следующие методы:
```go
type PathError struct {
	Op   string
	Path string
	Err  error
}
func (e *PathError) Error() string { return e.Op + " " + e.Path + ": " + e.Err.Error() }

func (e *PathError) Unwrap() error { return e.Err }

func (e *PathError) Timeout() bool {
    t, ok := e.Err.(interface{ Timeout() bool })
    return ok && t.Timeout()
}
```
Метод `Error()` определён для типа `*PathError`. Значит, переменная `err`,
определённая внутри функции `Foo()`, реализует интерфейс `error`
и мы можем вернуть её из функции в качестве `error` (https://go.dev/ref/spec#Method_sets).

Значение переменной `err` внутри `Foo()` равно nil,
поэтому первый вызов `Println(err)` выведет `<nil>`.
При этом метод `Error()` вызывается внутри `fmt.Println(err)`, но вызванная этим паника
отлавливается методом `func (p *pp) catchPanic(arg any, verb rune, method string)`
(/src/fmt/print.go, 536 строка):
```go
func (p *pp) catchPanic(arg any, verb rune, method string) {
    if err := recover(); err != nil {
        // If it's a nil pointer, just say "<nil>". The likeliest causes are a
        // Stringer that fails to guard against nil or a nil pointer for a
        // value receiver, and in either case, "<nil>" is a nice result.
        if v := reflect.ValueOf(arg); v.Kind() == reflect.Pointer && v.IsNil() {
            p.buf.writeString(nilAngleString)  // записываем в буфер ответа константу '<nil>'
            return
    }
    //ещё немного кода, который нам не важен
    }
}
```
Если в `main` явно вызвать `err.Error()`, программа упадёт с паникой,
но в этом случае никто её уже не отлавливает. Паника возникает из-за того, что
мы пытаемся вызвать метод от объекта, который не инициализировали. 
Обращение по адресу nil карается SIGSEGV.

Во втором вызове `Println(err == nil)`  `err` уже не конкретный тип, а интерфейс `error`.
Интерфейс равен nil тогда и только тогда, когда оба поля структуры `iface`/`eface` равны nil.
Так как мы "обернули" наш тип в интерфейс, то у этого интерфейса поля `tab` и `data` не nil.
Следовательно, сравнение `err` c nil в `main` вернёт false.
